name: Build

on:
  - pull_request

jobs:
  build_image:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Image
        run: docker build .
